meta_title: "Happy Home Management"
meta_description: "Rentals management for free (Beta testing)"
meta_image: "Logofav2.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@adinbrussels"